package io.openeden.trace

object TraceTag {
    const val CodebookHeuristicFallback = "codebook=HEURISTIC_FALLBACK"
    const val CodebookQuantized = "codebook=VQVAE_QUANTIZED"
    const val DiaryQueueOverflow = "diary=QUEUE_OVERFLOW"
    const val DiaryWritten = "diary=WRITTEN"
    const val VectorWriteSerialized = "vector=WRITE_SERIALIZED"
    const val HeartbeatSource = "source=HEARTBEAT"
    const val ShockStateTransition = "shock=STATE_TRANSITION"
    const val BackgroundDrift = "source=BACKGROUND_DRIFT"
    const val ShockStateDecayed = "shock=DECAYED"
    const val OmegaAccumulated = "omega=ACCUMULATED"
    const val RuntimeTickSessionFailed = "tick=SESSION_FAILED"
    const val MemoryWritten = "memory=WRITTEN"
    const val MemoryRetrieved = "memory=RETRIEVED"
    const val CentroidUpdated = "centroid=UPDATED"
    const val UserAffectInferred = "user_affect=INFERRED"
    const val UserAffectFallback = "user_affect=FALLBACK"
    const val UserAffectMapped = "user_affect=MAPPED"
    const val RelationshipLoaded = "relationship=LOADED"
    const val RelationshipUpdated = "relationship=UPDATED"
    const val RelationshipDegraded = "relationship=DEGRADED"
    const val IdentityAffinityApplied = "memory=IDENTITY_AFFINITY"
}
