package io.openeden.trace

object TraceTag {
    const val CodebookHeuristicFallback = "codebook=HEURISTIC_FALLBACK"
    const val CodebookQuantized = "codebook=VQVAE_QUANTIZED"
    const val LlmGroundingFailed = "llm=GROUNDING_FAILED"
    const val LlmGroundingRegenerated = "llm=REGENERATED"
    const val LlmGroundingRepaired = "llm=GROUNDING_REPAIRED"
    const val LlmGroundingRejected = "llm=GROUNDING_REJECTED"
    const val LlmCacheMeasured = "llm=CACHE_MEASURED"
    const val DiaryQueueOverflow = "diary=QUEUE_OVERFLOW"
    const val DiaryWritten = "diary=WRITTEN"
    const val VectorWriteSerialized = "vector=WRITE_SERIALIZED"
    const val TranscriptRetry = "transcript=ALREADY_COMMITTED"
    const val TranscriptDegraded = "transcript=DEGRADED"
    const val HeartbeatSource = "source=HEARTBEAT"
    const val ShockStateTransition = "shock=STATE_TRANSITION"
    const val BackgroundDrift = "source=BACKGROUND_DRIFT"
    const val ShockStateDecayed = "shock=DECAYED"
    const val OmegaAccumulated = "omega=ACCUMULATED"
    const val OmegaCritical = "omega=CRITICAL"
    const val RuntimeTickSessionFailed = "tick=SESSION_FAILED"
    const val RuntimeTickBaseline = "tick=BASELINE"
    const val MemoryWritten = "memory=WRITTEN"
    const val MemoryRetrieved = "memory=RETRIEVED"
    const val MemoryUtilityRejected = "memory=UTILITY_REJECTED"
    const val MemoryUtilityDegraded = "memory=UTILITY_DEGRADED"
    const val CentroidUpdated = "centroid=UPDATED"
    const val UserAffectInferred = "user_affect=INFERRED"
    const val UserAffectFallback = "user_affect=FALLBACK"
    const val UserAffectMapped = "user_affect=MAPPED"
    const val RelationshipLoaded = "relationship=LOADED"
    const val RelationshipUpdated = "relationship=UPDATED"
    const val RelationshipDegraded = "relationship=DEGRADED"
    const val IdentityAffinityApplied = "memory=IDENTITY_AFFINITY"
    const val VectorDatabaseQdrant = "vector_db=QDRANT"
    const val VectorDatabaseFallback = "vector_db=QDRANT_FALLBACK"
    const val VectorDatabaseRecovered = "vector_db=QDRANT_RECOVERED"
    const val VectorProjectionSucceeded = "vector_projection=SUCCEEDED"
    const val VectorProjectionRetry = "vector_projection=RETRY"
    const val VectorCollectionCreated = "vector_collection=CREATED"
    const val VectorCollectionRebuilt = "vector_collection=REBUILT"
}
