package io.openeden.relationship

enum class RelationshipEvidence {
    ORDINARY_INTERACTION,
    RESPECTED_PREFERENCE,
    CORRECTED_MISUNDERSTANDING,
    REPEATED_CONSISTENCY,
    RECIPROCAL_INTEREST,
    BOUNDARY_REQUEST,
    BOUNDARY_VIOLATION,
    CONFLICT,
    REPAIR,
}
